### ISSUE TITLE
Instance - RPCClientTimeoutError: Could not connect to [instance-name]. Please review the connection.

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/dashboard#123]
### Describe the bug

Testing dashboard using the latest version 1.26.0 and managed to create `hummingbot-master_bot_conf` however when creating instances under master_bot_conf, we are getting `RPCClientTimeoutError: Could not connect to.. Please review the connection.`

![image](https://github.com/hummingbot/dashboard/assets/73840223/5c9ef3ea-f3d1-4454-8ea7-d07d38cbdf19)

Check dashboard folder, `../hummingbot_files/bots/instance_name/logs/error.log
```
Traceback (most recent call last):
  File "/home/hummingbot/./bin/hummingbot_quickstart.py", line 15, in <module>
    from bin.hummingbot import UIStartListener, detect_available_port
  File "/home/hummingbot/bin/hummingbot.py", line 19, in <module>
    from hummingbot.client.hummingbot_application import HummingbotApplication
  File "/home/hummingbot/hummingbot/client/hummingbot_application.py", line 9, in <module>
    from hummingbot.client.command import __all__ as commands
  File "/home/hummingbot/hummingbot/client/command/__init__.py", line 2, in <module>
    from .config_command import ConfigCommand
  File "/home/hummingbot/hummingbot/client/command/config_command.py", line 8, in <module>
    from hummingbot.client.command.gateway_command import GatewayCommand
  File "/home/hummingbot/hummingbot/client/command/gateway_command.py", line 26, in <module>
    from hummingbot.client.ui.completer import load_completer
  File "/home/hummingbot/hummingbot/client/ui/completer.py", line 30, in <module>
    from hummingbot.strategy.strategy_v2_base import StrategyV2ConfigBase
  File "/home/hummingbot/hummingbot/strategy/strategy_v2_base.py", line 22, in <module>
    from hummingbot.smart_components.controllers.controller_base import ControllerBase, ControllerConfigBase
ModuleNotFoundError: No module named 'hummingbot.smart_components.controllers.controller_base'
```

Note: This seems related to an update from v2 strategy introducing controllers

### Steps to reproduce bug

1. Fresh install dashboard 
2. On Credentials, start `master config`
3. On Instance
  a. Start `hummingbot broker`
  b. Create new instance using latest (release version 1.26.0)

**Comment by klpanagi** [comment]
I get the same error

**Comment by Pomelog** [comment]
same same

**Comment by Detr0yt94** [comment]
same exact issue, please provide some help, thanks

**Comment by JesseXie** [comment]
it happens from hummingbot/hummingbot:version-1.26.0
