### ISSUE TITLE
Getting requirements to build wheel: finished with status 'error'

### ISSUE THREAD

**Issue by tushar11kh** [hummingbot/dashboard#144]
### Describe the bug

conda env create -f environment_conda.yml
Channels:
 - defaults
 - conda-forge
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: - Ran pip subprocess with arguments:
['/Users/tusharmac/miniconda3/envs/dashboard/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Users/tusharmac/Tushar IMP/OS_Project/dashboard/condaenv.5qinpr9t.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting hummingbot (from -r /Users/tusharmac/Tushar IMP/OS_Project/dashboard/condaenv.5qinpr9t.requirements.txt (line 1))
  Using cached hummingbot-20240530.tar.gz (7.2 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
      Traceback (most recent call last):
        File "/Users/tusharmac/miniconda3/envs/dashboard/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/tusharmac/miniconda3/envs/dashboard/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/tusharmac/miniconda3/envs/dashboard/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/rf/wnfkk9k57lj5r0fxcl98yc2c0000gn/T/pip-build-env-2up_yl1c/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/rf/wnfkk9k57lj5r0fxcl98yc2c0000gn/T/pip-build-env-2up_yl1c/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/rf/wnfkk9k57lj5r0fxcl98yc2c0000gn/T/pip-build-env-2up_yl1c/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/rf/wnfkk9k57lj5r0fxcl98yc2c0000gn/T/pip-build-env-2up_yl1c/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 165, in <module>
        File "<string>", line 153, in main
        File "/private/var/folders/rf/wnfkk9k57lj5r0fxcl98yc2c0000gn/T/pip-build-env-2up_yl1c/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 979, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/private/var/folders/rf/wnfkk9k57lj5r0fxcl98yc2c0000gn/T/pip-build-env-2up_yl1c/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 821, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/private/var/folders/rf/wnfkk9k57lj5r0fxcl98yc2c0000gn/T/pip-build-env-2up_yl1c/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 116, in nonempty
          raise ValueError(error_msg)
      ValueError: 'hummingbot/**/*.pyx' doesn't match any files
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

failed

CondaEnvException: Pip failed

I cloned an old branch named update-workflow-1, it worked but it is missing a lot of features.

I believe it is referring to this https://github.com/hummingbot/hummingbot/blob/master/setup.py.

### Steps to reproduce bug

1. git clone https://github.com/hummingbot/dashboard.git
2.  cd dashboard
3. make install

**Comment by rapcmia** [comment]
Followed steps to reproduce on dashboard and able to build .whl on both mac(m1) and ubuntu(24.04) ✅
