### ISSUE TITLE
Rebalance configuration - Rebalance does not update the min_order_amount_in_usd when modified 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/dashboard#209]
### Describe the bug

When testing Hyperliquid on dashboard with rebalance enabled on one of my configs, observed that it does not change the amount used to rebalance even when we modified it on `./bots/scripts/v2_with_controller` using `min_amount_to_rebalance_usd`

![image](https://github.com/user-attachments/assets/c40c4405-fd28-4160-a778-22c4b687b57a)
- On our tests it still uses a value equivalent to the default 8usd
  ```
  2024-11-29 13:09:23,003 - 15 - hummingbot.strategy.script_strategy_base - INFO - Rebalance: Buying for a higher value to avoid future imbalance 1.752925193917349577106796967 HYPE to USDC. Balance: 11.04596702000000000000000 | Executors unmatched balance 0E-27
  2024-11-29 13:09:23,488 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1732885763.0, "order_id": "0xda1ddbd752e69ff2814d3692c6a7e599", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "hyperliquid"}
  2024-11-29 13:09:23,489 - 15 - hummingbot.connector.client_order_tracker - INFO - Order 0xda1ddbd752e69ff2814d3692c6a7e599 has failed. Order Update: OrderUpdate(trading_pair='HYPE-USDC', update_timestamp=1732885763.397, new_state=<OrderState.FAILED: 6>, client_order_id='0xda1ddbd752e69ff2814d3692c6a7e599', exchange_order_id='51280110911', misc_updates=None)
  2024-11-29 13:09:23,489 - 15 - hummingbot.connector.exchange.hyperliquid.hyperliquid_exchange.HyperliquidExchange - NETWORK - Error submitting buy MARKET order to Hyperliquid for 1.75 HYPE-USDC 4.7919999999999998152588887023739516735076904296875.
  Traceback (most recent call last):
    File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
      await self._place_order_and_process_update(order=order, **kwargs,)
    File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
      exchange_order_id, update_timestamp = await self._place_order(
    File "/home/hummingbot/hummingbot/connector/exchange/hyperliquid/hyperliquid_exchange.py", line 388, in _place_order
      raise IOError(f"Error submitting order {order_id}: {o_order_result['error']}")
  OSError: Error submitting order 0xda1ddbd752e69ff2814d3692c6a7e599: Order must have minimum value of $10. asset=10107
  2024-11-29 13:09:23,490 - 15 - hummingbot.connector.exchange.hyperliquid.hyperliquid_exchange.HyperliquidExchange - WARNING - Failed to submit BUY order to Hyperliquid. Check API key and network connection.
  ```

### Steps to reproduce bug

1. Setup any spot connector on selected controller-config
2. Deploy with rebalance enabled
3. Observe the bot when retrying to submit a market order to rebalance

**Comment by rapcmia** [comment]
Rebalance has been removed from script-config
